### PR TITLE
readme

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by sils1297** [comment]
@rultor mere

**Comment by sils1297** [comment]
@rultor merge

**Comment by AbdealiJK** [comment]
rultor isnt active yet ?

**Comment by AbdealiJK** [comment]
@rultor hello

**Comment by sils1297** [comment]
@AbdealiJK rultor will get notified on any repository. Rultor already should have permission because its n the coala contributors team and that has permissions to all our repos.

**Comment by AbdealiJK** [comment]
cool

**Pull request merged**
